// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hjwxbpmoyjkgydptjklw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhqd3hicG1veWprZ3lkcHRqa2x3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3OTM2NjEsImV4cCI6MjA2NTM2OTY2MX0.Lb_gm42eW57ETf-tqmoslyedWkxSh6nLbO7R5mZgRV0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});